CREATE TABLE user (
	ID INTEGER(30) AUTO_INCREMENT PRIMARY KEY,
	USER_NAME VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL
);

CREATE TABLE workout (
	ID INTEGER(30) AUTO_INCREMENT PRIMARY KEY,
	USER_ID INTEGER(30) AUTO_INCREMENT,
	CURRENT_DATE DATE 
);

CREATE TABLE exercise (
	ID INTEGER(30) AUTO_INCREMENT PRIMARY_KEY
	WORKOUT_ID INTEGER(30),
	NAME VARCHAR(30),
	SETS INTEGER(10),
	REPS INTEGER(10),
	WEIGHT INTEGER(10),
	SUCCESS BOOLEAN
);

ALTER TABLE workout ADD FOREIGN KEY (USER_ID) REFERENCES user(ID) ON DELETE CASCADE;
ALTER TABLE exercise ADD FOREIGN KEY (WORKOUT_ID) REFERENCES workout(ID) ON DELETE CASCADE;